<?php

namespace ContainerWaffkF6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q08ZHKUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q08ZHKU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q08ZHKU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored..service_locator.q08ZHKU.http\\Client\\Request', NULL, 'Cannot autowire service ".service_locator.q08ZHKU": it references class "http\\Client\\Request" but no such service exists.'],
        ], [
            'request' => 'http\\Client\\Request',
        ]);
    }
}
