<?php

namespace ContainerWaffkF6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YrZtgZ0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yrZtgZ0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yrZtgZ0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ProductController::list' => ['privates', '.service_locator.uGACkMP', 'get_ServiceLocator_UGACkMPService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.jsuHsHQ', 'get_ServiceLocator_JsuHsHQService', true],
            'App\\Controller\\UserController::welcome' => ['privates', '.service_locator.q08ZHKU', 'get_ServiceLocator_Q08ZHKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ProductController:list' => ['privates', '.service_locator.uGACkMP', 'get_ServiceLocator_UGACkMPService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.jsuHsHQ', 'get_ServiceLocator_JsuHsHQService', true],
            'App\\Controller\\UserController:welcome' => ['privates', '.service_locator.q08ZHKU', 'get_ServiceLocator_Q08ZHKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ProductController::list' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\UserController::welcome' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProductController:list' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\UserController:welcome' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
