<?php

namespace ContainerNNewhxu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q08ZHKU.http\Client\Request' shared service.
     *
     * @return \http\Client\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q08ZHKU": it references class "http\\Client\\Request" but no such service exists.');
    }
}
