<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7pMsKYX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7pMsKYX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7pMsKYX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7pMsKYX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7pMsKYX\App_KernelDevDebugContainer([
    'container.build_hash' => '7pMsKYX',
    'container.build_id' => '4db6b24c',
    'container.build_time' => 1718483679,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7pMsKYX');
